# Generated by Django 4.2.16 on 2025-06-04 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_client_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('CREDIT', 'Crédit'), ('REMBOURSEMENT', 'Remboursement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='date_ouverture',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='type_compte',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='date_credit',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='montant_rembourse',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='date_remboursement',
        ),
        migrations.AddField(
            model_name='client',
            name='date_inscription',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 6, 4, 18, 34, 47, 268746)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compte',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='date_octroi',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='credit',
            name='duree_mois',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remboursement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compte',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.client'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='statut',
            field=models.CharField(default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='credit',
            name='taux_interet',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.credit'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='mouvement',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.compte'),
        ),
        migrations.AddField(
            model_name='historiquetransaction',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.compte'),
        ),
    ]
