# Generated by Django 4.2.16 on 2025-06-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_client_agent_credit_agent_mouvement_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identifiant',
            field=models.CharField(default='ID0000000', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compte',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='gestion.client'),
        ),
    ]
