# Generated by Django 4.2.16 on 2025-06-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_client_identifiant_alter_compte_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='type_compte',
            field=models.CharField(choices=[('epargne', 'Épargne'), ('courant', 'Courant')], default='epargne', max_length=20),
        ),
    ]
