# Generated by Django 4.2.16 on 2025-06-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_client_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='gestion.compte'),
        ),
    ]
