# Generated by Django 4.2.16 on 2025-06-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_mouvement_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='numero_credit',
            field=models.CharField(default='CR0000000', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
