# Generated by Django 4.2.16 on 2025-06-16 09:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_credit_numero_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='remboursement',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='methode_paiement',
            field=models.CharField(default='INCONNU', max_length=50),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='montant_interet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='montant_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remboursement',
            name='numero_remboursement',
            field=models.CharField(default='REM00010000000000', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remboursement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='gestion.credit'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
