# Generated by Django 4.2.16 on 2025-06-16 13:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remboursement_agent_remboursement_methode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='montant_rembourse',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total déjà remboursé pour ce crédit.', max_digits=12),
        ),
    ]
