# Generated by Django 4.2.16 on 2025-06-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_credit_montant_rembourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('superviseur', 'Superviseur'), ('agent', 'Agent')], default='agent', max_length=15),
        ),
    ]
