# Generated by Django 4.2.16 on 2025-06-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_historiquetransaction_agent_alter_compte_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='agent',
        ),
    ]
