# Generated by Django 4.2.16 on 2025-06-17 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_credit_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquetransaction',
            name='agent',
        ),
        migrations.AddField(
            model_name='credit',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
