# Generated by Django 4.2.16 on 2025-06-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_historiquetransaction_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquetransaction',
            name='agent',
        ),
    ]
