# Generated by Django 4.2.16 on 2025-06-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_remove_historiquetransaction_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('superviseur', 'Superviseur')], default='agent', max_length=15),
        ),
    ]
